# Generated by AI.
extends RefCounted
class_name GarlicTest
## Garlic 词法/语法分析器单元测试。
## 运行方式：运行 addons/shrimpvm/scenes/test.tscn 场景（编辑器 F6 或
## godot46 --headless --path <项目> res://addons/shrimpvm/scenes/test.tscn），
## 结果输出到输出/错误面板。

var _case_failures: PackedStringArray = []


static func test() -> void:
	var tester := GarlicTest.new()
	tester._run_all()


# ---------------------------------------------------------------- 断言辅助

func _assert_eq(actual, expected, label: String) -> void:
	if actual != expected:
		_case_failures.append("%s: 期望 %s, 实际 %s" % [label, str(expected), str(actual)])


func _assert_true(cond: bool, label: String) -> void:
	if not cond:
		_case_failures.append(label)


func _assert_null(value, label: String) -> void:
	if value != null:
		_case_failures.append("%s: 期望 null, 实际 %s" % [label, str(value)])


## 断言源码解析成功并返回期望结果
func _assert_parses(source: String, expected: Variant, label: String) -> void:
	var result: Variant = GarlicParser.parse(source)
	if result == null:
		_case_failures.append("%s: 解析失败（源码：%s）" % [label, source])
		return
	var expected_text := var_to_str(expected).replace("\n", " ")
	var actual_text := var_to_str(result).replace("\n", " ")
	if expected_text != actual_text:
		_case_failures.append("%s: 期望 %s, 实际 %s" % [label, expected_text, actual_text])


## 断言源码必须解析失败
func _assert_rejects(source: String, label: String) -> void:
	var result: Variant = GarlicParser.parse(source)
	_assert_null(result, "%s（源码：%s）应被拒绝" % [label, source])


# ---------------------------------------------------------------- 运行器

func _run_all() -> void:
	var cases: Array[String] = [
		"_test_single_node",
		"_test_bare_body_file",
		"_test_example_file",
		"_test_literals",
		"_test_string_name",
		"_test_escapes",
		"_test_array_literal",
		"_test_trailing_comma",
		"_test_empty_node_and_body",
		"_test_negative_number",
		"_test_nested_comment",
		"_test_reject_missing_value",
		"_test_reject_node_in_array",
		"_test_reject_duplicate_attribute",
		"_test_reject_non_node_in_body",
		"_test_reject_missing_semicolon",
		"_test_reject_reserved_word_as_ident",
		"_test_reject_trailing_content",
		"_test_reject_unterminated",
		"_test_reject_empty_file",
		"_test_reject_nested_array",
	]
	var passed := 0
	for case in cases:
		_case_failures = PackedStringArray()
		call(case)
		if _case_failures.is_empty():
			passed += 1
			print("[PASS] %s" % case)
		else:
			for failure in _case_failures:
				printerr("[FAIL] %s -> %s" % [case, failure])
	print("GarlicTest: %d/%d 用例通过" % [passed, cases.size()])


# ---------------------------------------------------------------- 用例

func _test_single_node() -> void:
	_assert_parses("foo(a=1,b=\"x\")", {"type": "foo", "a": 1.0, "b": "x"}, "单节点")


func _test_bare_body_file() -> void:
	var result: Variant = GarlicParser.parse("{alpha(x=1);beta();}")
	_assert_true(result is Array, "裸节点体应解析为数组")
	if result is Array:
		_assert_eq(result.size(), 2, "节点体长度")
		_assert_eq(var_to_str(result[0]), var_to_str({"type": "alpha", "x": 1.0}), "节点体首项")
		_assert_eq(var_to_str(result[1]), var_to_str({"type": "beta"}), "节点体次项")


func _test_example_file() -> void:
	var file := FileAccess.open("res://addons/shrimpvm/garlic/examples/add.srp", FileAccess.READ)
	_assert_true(file != null, "示例文件应可读取")
	if file == null:
		return
	var expect := {
		"type": "root",
		"body": [
			{"type": "function_definition", "name": "add", "params": ["a", "b"], "body": [
				{"type": "return", "data": {"type": "add",
					"A": {"type": "read_symbol", "name": "a"},
					"B": {"type": "read_symbol", "name": "b"}}},
			]},
			{"type": "print", "content": {"type": "function_call", "name": "add", "params": [
				{"type": "number_literal", "content": 123.0},
				{"type": "number_literal", "content": 123.0},
			]}},
		],
	}
	_assert_parses(file.get_as_text(), expect, "示例文件 add.srp")


func _test_literals() -> void:
	_assert_parses("n(a=123456,b=114.514,c=true,d=false)",
			{"type": "n", "a": 123456.0, "b": 114.514, "c": true, "d": false}, "基本字面量")


func _test_string_name() -> void:
	var result: Variant = GarlicParser.parse("s(a=\"x\",b='y',c=`z`,d=「sn」)")
	_assert_true(result != null, "各种引号应可解析")
	if result != null:
		_assert_eq(result.a, "x", "双引号字符串")
		_assert_eq(result.b, "y", "单引号字符串")
		_assert_eq(result.c, "z", "反引号字符串")
		_assert_eq(result.d, StringName("sn"), "「」应解析为 StringName")
		_assert_true(result.d is StringName, "「」结果类型应为 StringName")


func _test_escapes() -> void:
	_assert_parses("s(a=\"a\\nb\",b=\"He said \\\"ok\\\"\")",
			{"type": "s", "a": "a\nb", "b": "He said \"ok\""}, "反斜杠转义")


func _test_array_literal() -> void:
	_assert_parses("a(x=[114,514,1919.810])",
			{"type": "a", "x": [114.0, 514.0, 1919.81]}, "数字数组")
	_assert_parses("a(x=[\"Hello\",'World!',true,false])",
			{"type": "a", "x": ["Hello", "World!", true, false]}, "混合数组")


func _test_trailing_comma() -> void:
	_assert_parses("f(a=1,b=2,)", {"type": "f", "a": 1.0, "b": 2.0}, "节点属性后缀逗号")
	_assert_parses("f(a=[1,2,])", {"type": "f", "a": [1.0, 2.0]}, "数组后缀逗号")


func _test_empty_node_and_body() -> void:
	_assert_parses("foo()", {"type": "foo"}, "空属性节点")
	_assert_parses("foo(a={})", {"type": "foo", "a": []}, "空节点体")


func _test_negative_number() -> void:
	_assert_parses("n(v=-114.514)", {"type": "n", "v": - 114.514}, "负数字面量")


func _test_nested_comment() -> void:
	_assert_parses("f(<outer <inner> more> a=1)", {"type": "f", "a": 1.0}, "嵌套注释等价于空白")


# ---------------------------------------------------------------- 非法用例

func _test_reject_missing_value() -> void:
	_assert_rejects("foo(a=)", "属性缺少值")


func _test_reject_node_in_array() -> void:
	_assert_rejects("foo(a=[number_literal(content=1)])", "数组内不能放节点")


func _test_reject_duplicate_attribute() -> void:
	_assert_rejects("foo(a=1, a=2)", "属性声明重复")


func _test_reject_non_node_in_body() -> void:
	_assert_rejects("foo(a={2})", "节点体内有非节点要素")


func _test_reject_missing_semicolon() -> void:
	_assert_rejects("foo(a={number_literal(content=1)})", "节点语句末尾缺少分号")


func _test_reject_reserved_word_as_ident() -> void:
	_assert_rejects("true(x=1)", "保留字不能作节点名")
	_assert_rejects("foo(true=1)", "保留字不能作属性名")


func _test_reject_trailing_content() -> void:
	_assert_rejects("foo(a=1) bar()", "文件末尾有多余内容")
	_assert_rejects("foo(a=1) 114", "文件末尾有多余字面量")


func _test_reject_unterminated() -> void:
	_assert_rejects("foo(a=\"unterminated)", "未闭合字符串")
	_assert_rejects("foo(a=\"mixed'y)", "引号必须配对")
	_assert_rejects("foo(a=1", "未闭合括号")
	_assert_rejects("<unclosed comment", "未闭合注释")
	_assert_rejects("{alpha(x=1);", "未闭合节点体")


func _test_reject_empty_file() -> void:
	_assert_rejects("", "空文件")
	_assert_rejects("   <only comment>  ", "仅含注释的文件")


func _test_reject_nested_array() -> void:
	_assert_rejects("foo(a=[1,[2]])", "数组不能嵌套")
