# Generated by AI.
extends RefCounted
class_name WrapperContextTest
## WrapperContext 单元测试。由 addons/shrimpvm/scenes/test.tscn 调用。
## 契约：
##   get_pointer()  —— 将 pointer 解析到 tree 上的当前节点
##   run(path)      —— 返回 pointer + path 解析到的值，不修改 context
##   forward(path)  —— 返回一个新的 WrapperContext（pointer 移动到 pointer + path），不修改当前 context

var _case_failures: PackedStringArray = []


static func test() -> void:
	var tester := WrapperContextTest.new()
	tester._run_all()


# ---------------------------------------------------------------- 断言辅助

func _assert_eq(actual, expected, label: String) -> void:
	if actual != expected:
		_case_failures.append("%s: 期望 %s, 实际 %s" % [label, str(expected), str(actual)])


func _assert_null(value, label: String) -> void:
	if value != null:
		_case_failures.append("%s: 期望 null, 实际 %s" % [label, str(value)])


func _assert_true(cond: bool, label: String) -> void:
	if not cond:
		_case_failures.append(label)


# ---------------------------------------------------------------- 运行器

func _run_all() -> void:
	var cases: Array[String] = [
		"_test_get_pointer_self",
		"_test_get_pointer_nested",
		"_test_run_attribute",
		"_test_run_index",
		"_test_run_keeps_context",
		"_test_forward_returns_new_context",
		"_test_forward_index",
		"_test_forward_parent_and_root",
		"_test_type_mismatch_returns_null",
	]
	var passed := 0
	for case in cases:
		_case_failures = PackedStringArray()
		call(case)
		if _case_failures.is_empty():
			passed += 1
			print("[PASS] %s" % case)
		else:
			for failure in _case_failures:
				printerr("[FAIL] %s -> %s" % [case, failure])
	print("WrapperContextTest: %d/%d 用例通过" % [passed, cases.size()])


# ---------------------------------------------------------------- 夹具

func _fixture() -> Dictionary:
	return {
		"a": {"b": 1, "c": [10, 20]},
		"d": 3,
	}


func _make_context(data, pointer_classpath: String = "#") -> WrapperContext:
	return WrapperContext.new(data,WrapperPath.from(pointer_classpath).normalize())


# ---------------------------------------------------------------- 用例

## SELF 指针应指向整棵树
func _test_get_pointer_self() -> void:
	var tree := _fixture()
	var ctx := _make_context(tree)
	_assert_eq(ctx.get_pointer(), tree, "SELF 指针应指向整棵树")


## 嵌套属性指针应解析到对应节点
func _test_get_pointer_nested() -> void:
	var ctx := _make_context(_fixture(), "a.b")
	_assert_eq(ctx.get_pointer(), 1, "指针应解析到嵌套节点")


## run() 应解析属性段并返回值
func _test_run_attribute() -> void:
	var ctx := _make_context(_fixture())
	_assert_eq(ctx.run(WrapperPath.from("a.b")), 1, "run 应返回属性值")


## run() 应解析索引段并返回元素
func _test_run_index() -> void:
	var ctx := _make_context(_fixture())
	_assert_eq(ctx.run(WrapperPath.from("a.c.[1]")), 20, "run 应返回索引元素")


## run() 不应修改当前 context
func _test_run_keeps_context() -> void:
	var tree := _fixture()
	var ctx := _make_context(tree)
	ctx.run(WrapperPath.from("a.b"))
	_assert_eq(ctx.pointer._to_string(), "#", "run 不应移动指针")
	_assert_eq(ctx.get_pointer(), tree, "run 后当前节点不变")


## forward() 应返回新 context，且不修改当前 context
func _test_forward_returns_new_context() -> void:
	var tree := _fixture()
	var ctx := _make_context(tree)
	var next := ctx.forward(WrapperPath.from("a.c"))
	_assert_eq(next.get_pointer(), [10, 20], "新 context 应指向子树")
	_assert_eq(next.pointer._to_string(), "a.c", "新 context 的指针应移动")
	_assert_true(next != ctx, "forward 应返回新 context")
	_assert_eq(ctx.pointer._to_string(), "#", "当前 context 的指针不应被修改")
	_assert_eq(ctx.get_pointer(), tree, "当前 context 的节点不应被修改")


## forward() 应支持数组索引段，且可链式前进
func _test_forward_index() -> void:
	var ctx := _make_context(_fixture())
	var next := ctx.forward(WrapperPath.from("a.c")).forward(WrapperPath.from("[0]"))
	_assert_eq(next.get_pointer(), 10, "链式 forward 索引应返回元素")
	_assert_eq(next.pointer._to_string(), "a.c.[0]", "指针应包含索引段")


## forward() 支持 "<"（../）回上级与 "/"（绝对路径）回树根
func _test_forward_parent_and_root() -> void:
	var tree := _fixture()
	var ctx := _make_context(tree)
	var back := ctx.forward(WrapperPath.from("a")).forward(WrapperPath.from("<"))
	_assert_eq(back.get_pointer(), tree, "\"<\" 应回到上级")
	var root := ctx.forward(WrapperPath.from("/"))
	_assert_eq(root.get_pointer(), tree, "\"/\" 应回到树根")


## 类型不匹配（字典上取索引 / 数组上取属性）应返回 null
func _test_type_mismatch_returns_null() -> void:
	var ctx := _make_context(_fixture())
	_assert_null(ctx.run(WrapperPath.from("a.c.x")), "数组上取属性应返回 null")
	var moved := ctx.forward(WrapperPath.from("a"))
	_assert_null(moved.run(WrapperPath.from("[0]")), "字典上取索引应返回 null")
